name: Build macOS

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: .

      - name: Build macOS
        working-directory: app
        run: flutter build macos --release

      - name: Prepare file path
        run: |
          FILE_PATH="app/build/macos/Build/Products/Release/TTS Narrator.app"
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

      - name: Create Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v3.0.3
        with:
          files: ${{ env.FILE_PATH }}
          token: ${{ secrets.GITHUB_TOKEN }}
